[package]
name = "apod_wall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking"] }
serde_json = "1.0"
tempfile = "3.3"
wallpaper = "3.2"